name: ir
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  url_launcher: ^6.2.5
  http: ^1.2.1
  dartz: ^0.10.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.4
  loading_animation_widget: ^1.2.0+4
  path: ^1.9.0
  rename: ^3.0.2
  intl: ^0.18.1
  rxdart:
  bloc_concurrency:
  infinite_scroll_pagination:
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1

flutter_gen:
  output: lib/core/style/assets
  integrations:
    flutter_svg: true
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/font/ProductSans/ProductSans-Black.ttf
          weight: 900
        - asset: assets/font/ProductSans/ProductSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/font/ProductSans/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/font/ProductSans/ProductSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/ProductSans/ProductSans-Italic.ttf
          weight: 400
        - asset: assets/font/ProductSans/ProductSans-Light.ttf
          weight: 300
        - asset: assets/font/ProductSans/ProductSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/ProductSans/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/font/ProductSans/ProductSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/ProductSans/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/font/ProductSans/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/font/ProductSans/ProductSans-ThinItalic.ttf
          weight: 100
          style: italic